# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: msimonne <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/24 16:37:47 by msimonne          #+#    #+#              #
#    Updated: 2020/10/24 16:50:43 by msimonne         ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

SRC = src/*.c

CFLAGS = -Wall -Wextra -Werror

all:
	gcc $(CFLAGS) -o $(NAME) $(SRC)

clean:
	 rm -f *.o

fclean: clean
	rm -f $(NAME)
